version: 1
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
  mnemonic: harbor reform medal decorate situate village kiss reason usual clown prepare oil any army senior palace film fun donate time loud onion together tuna

- name: bob
  coins:
  - 10000token
  - 100000000stake
  mnemonic: jaguar essay wall hole verb great army panda aerobic age feed soul nominee hurdle inner board theme velvet grief above swing subject margin manage 

faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
client:
  typescript:
    path: ts-client
  hooks:
    path: react/src/hooks
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 100000000stake
