version: 1
accounts:
- name: alice
  coins:
  - 10000000000000000000token
  - 210000000000000000000stake
  mnemonic: harbor reform medal decorate situate village kiss reason usual clown prepare oil any army senior palace film fun donate time loud onion together tuna

- name: bob
  coins:
  - 10000000000000000000token
  - 110000000000000000000stake
  mnemonic: jaguar essay wall hole verb great army panda aerobic age feed soul nominee hurdle inner board theme velvet grief above swing subject margin manage 

- name: wasm
  coins:
  - 10000000000000000000token
  - 110000000000000000000stake
  mnemonic: guilt access minute cereal stage eight stuff replace chunk day before gallery idea wash stomach sun behind gesture old twist card afraid board sadness 

faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
client:
  typescript:
    path: ts-client
  hooks:
    path: react/src/hooks
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 100000000stake
